name: first example
on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4.2.2
        
        - name: Startup message
          run: echo "Startup message"
        
        - name: List files
          run: ls

        - name: Read license
          run: cat LICENSE