name: first example
on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4.2.2
        
        - name: Startup message
          run: |
            echo "Startup message"
            pwd
            ls
            cat README.md

        - name: Generate ASCII Artwork
          run: cosway -f dragon "Run for cover, I am a dragon...RRAAWR" >> dragon.txt
        
        # - name: List files
        #   run: ls

        # - name: Read license
        #   run: cat LICENSE